require_relative 'default_price'
require_relative 'rental'
require_relative 'customer'
require_relative 'regular_price'
require_relative 'new_release_price'
require_relative 'childrens_price'
require_relative 'movie'